"use client";
// src/useStore.js
import { create } from "zustand";
const translations = {
  en: {
    navbar: {
      home: "Home",
      features: "Features",
      howitworks: "How it works",
      download: "Download",
      signup: "Sign Up",
      login: "Login",
      lang: "عربي",
    },
    section1: {
      unlock: "Unlock",
      potential: "the Potential of",
      gold: "Gold.",
      text: "Our user-friendly app makes investing in gold simple and secure.",
      download: "Download the App",
      goldPriceUpdate: "Gold price updated at",
      buy: "Buy - 24K ",
      sell: "Sell - 24K ",
      egp: "EGP",
    },
    section2: {
      why: "Why",
      sabika: "Sabika?",
      buy: "Buy & Sell gold",
      fraction: "Fractions",
      track: "Track",
      your: "Your Investment",
      portfolio: "Portfolio.",
      secure: "Secure",
      transaction: "Transactions & Wallet",
      management: "Management.",
      enjoy: "Enjoy A",
      seamless: "Seamless Experience.",
    },
    section3: {
      what: "What we",
      offer: "Offer?",
      lowest: "Lowest Price",
      market: "in the Market!",
      effort:
        "Effortlessly own a piece of the gold market! Buy and sell gold fractions at unbeatable prices with our competitive service fees.",
      user: "User-friendly",
      app: "app interface.",
      sabika: "Sabika",
      makes:
        "makes buying and selling gold a breeze, allowing you to navigate with ease and manage your investments effortlessly.",
    },
    section4: {
      how: "How do I",
      start: "start?",
      download: "Download",
      downloadText: "Download the Sabika app from your app store.",
      signup: "SignUp",
      signupText: "Create an account to begin trading.",
      deposit: "Deposit Funds",
      depositText: "Add funds to start investing in gold.",
      trade: "Trade Gold",
      tradeText: "Start trading gold with ease.",
    },
    section5: {
      take: "Take",
      control: "Control",
      of: "of Your",
      financial: "Financial Future",
      with: "with",
      sabika: "Sabika!",
    },
    footer: {
      privacy: "Privacy Policy",
      terms: "Terms And Conditions",
    },
    header: {
      wallet: "Wallet",
      portfolio: "Portfolio",
      dashboard: "Dashboard",
      account: "Account",
      language: "Language",
      logout: "Logout",
    },
    wallet: {
      total: "Total Balance",
      totalToolTip: " This is the total balance of your wallet",
      available: "Available",
      availableToolTip:
        "This is the total amount of money you have in your wallet",
      availableWithDraw: "Available for Withdrawal",
      availableWithDrawToolTip:
        "This is the total amount of money you can withdraw",
      processing: "Processing",
      processingToolTip:
        "This is the total amount of money that is currently processing",
      totalStorageFees: "Total Storage Fees",
      totalStorageFeesToolTip:
        "This is the total amount of money you have paid for storage fees",
      hide: "Hide Balance",
      add: "Add Balance",
      withdraw: "Withdraw",
      moneyHistory: "Money Transaction History",
      goldHistory: "Gold Transaction History",
      deposit: "Deposit",
      purchase: "Purchase",
      sell: "Sell",
      seeAll: "See all",
      reset: " Reset",
      egp: "EGP",
      gram: "Gram",
      grams: "Grams",
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
      show: "Show Balance",
      refund: "Refund",
      storeFees: "Storage Fees",
      buy: "Buy",
      startDate: "Start Date",
      endDate: "End Date",
      noTransaction: " No Transactions Found",
      cancelationFees: "Cancelation Fees",
      transactionDetails: "Transaction Details",
      transactionStatus: " Transaction Status",
      transactionId: "Transaction ID",
      transactionDate: "Transaction Date",
      transactionType: "Transaction Type",
      transactionTime: "Transaction Time",
      goldPrice: "Gold Price",
      totalWeight: "Total Weight",
      price: "Price",
      manufacturingFees: "Manufacturing Fees",
      taxes: "Taxes",
      transactionFee: "Transaction Fee",
      storageFee: "Storage Fee",
      total: "Total",
      serialNumbers: "Serial Numbers",
      filter: "Filter",
      noTransactions: "No Transactions Found",
      noTransactionYet: "  No Transactions Yet",
      viewSerials: "View Serials",
      serialNumber: "Serial Numbers",
      noGoldTransactionsYet: "No Gold Transactions Yet",
    },
    dashboard: {
      totalAssets: "Total balance",
      totalAssetsToolTip: "This is the total balance you have in your wallet",
      available: "Available",
      availableToolTip:
        "This is the total amount of money you have in your wallet",
      goldAssets: "Gold Asset  ",
      goldAssetsToolTip:
        "This is the total amount of gold you have in your wallet",
      processing: "Processing",
      processingToolTip:
        "This is the total amount of money that is currently processing",
      lastUpdate: "Last Update at",
      gold24KAskPrice: "Gold 24K Buy Price",
      gold24KBuy: "Buy - 24K (Fees Excluded)",
      gold24KSell: "Sell - 24K (Fees Excluded)",
      gold24KBidPrice: "  Gold 24K Sell Price",
      title: "Dashboard",
      goldPriceChart: "Gold Price Chart",
      updated: "Gold price updated at",
    },
    buySell: {
      weightPlaceholder: "Enter Weight",
      moneyPlaceholder: "Enter Amount",
      totalWeight: "Total Weight",
      available: "Available",
      buy: "Buy",
      sell: "Sell",
      weight: "Weight",
      money: "Amount",
      sellAll: "Sell All",
      grams: "Grams",
      egp: "EGP",
      min: "Min",
      max: "Max",
      showBalance: "Show Balance",
      hideBalance: "Hide Balance",
      goldFractionCalculator: "Gold Fraction Calculator",
    },
    pinCode: {
      title: "Please enter the PIN code to proceed.",
      cancel: "Cancel",
      confirm: "Confirm",
      confirmPayment: "Confirm Payment",
      wrongPin: "Wrong PIN Code",
    },
    purchase: {
      confirmBuy: "Confirm Buy",
      confirmSell: "Confirm Sell",
      secureGold:
        "Your gold is securely stored in Central Bank of Egypt , Please be aware that delivery of the Gold Fractions is not available. ",
      sellTalk:
        "You must withdraw your money within 2 months after selling. If you don’t, it will be automatically moved to your bank account.",
      voucher: "Enter Voucher Code",
      successVoucher: "A voucher has been applied to your order",
      failedVoucher: "The voucher code you entered is invalid",
      goldPrice: "Gold Price",
      totalWeight: "Total Weight",
      valueOfGold: "Value of Gold",
      ManufacturingFee: "Manufacturing Fee",
      Taxes: "Taxes",
      TransactionFee: "Transaction Fee",
      StorageFee: "Storage Fee",
      total: "Total",
      Discount: "Discount Applied",
      Amount: "Amount Due",
      confirmPayment: "Confirm Payment",
      apply: "Apply",
      amountWeReceive: "Amount You’ll Receive",
      current: "Current Gold Price",
      totalWeightToSell: "Total weight to Sell ",
      yourPurchase: "Your Purchase was successful!",
      gramOfGold:
        "gram of gold you purchased has been added to your total gold balance.",
      portfolio: "Portfolio",
      yourGold: "Your gold has been sold !",
      yourGoldSale:
        "Your gold sale went through, and the funds have been added to your wallet.",
      wallet: "Wallet",
      viewTransaction: "View Transaction",
    },
    login: {
      welcome: "Welcome back to",
      sabika: "Sabika",
      join: "Join our community and enjoy a",
      seamless: "seamless, Shariah-compliant experience.",
      phoneOrEmail: "Phone Number or E-mail",
      login: "Login",
      invalid: "Invalid Phone Number or E-mail",
      buySell: "Buy & Sell Gold",
      fraction: "Fractions",
      track: "Track",
      Your: "Your Investment",
      portfolio: "Portfolio",
      secure: "Secure",
      Transactions: "Transactions & Wallet",
      Management: "Management",
      join: "Join",
      for: "For A",
      seamless: "Seamless, Trusted & Shariah-compliant",
      Journey: "Journey",
    },
    otp: {
      verify: "Verify Your Identity",
      enter:
        "Enter the OTP we sent to your phone or email to verify your account and complete the login process.",
      verifyButton: "Verify",
      receive: "Didn’t receive the code?",
      resend: "Resend code",
      wrong: "Wrong OTP",
      fill: "Please Fill All Fields",
    },
  },
  ar: {
    navbar: {
      home: "الرئيسيه",
      features: "المميزات",
      howitworks: "كيفية البدأ",
      download: "تحميل",
      signup: "تسجيل الدخول",
      lang: "English",
      login: "تسجيل الدخول",
    },
    section1: {
      unlock: "استكشف",
      potential: "إمكانات",
      gold: "الذهب",
      text: "تطبيقنا سهل الاستخدام يجعل الاستثمار في الذهب بسيطًا وآمنًا",
      download: "حمل التطبيق",
      goldPriceUpdate: "تم تحديث سعر الذهب بتاريخ",
      buy: "شراء - 24K ",
      sell: "بيع - 24K ",
      egp: "جنيه  ",
    },
    section2: {
      why: "لماذا",
      sabika: "سبيكة ؟",
      buy: "بيع و شراء",
      fraction: "جزيئات الذهب",
      track: "تتبع",
      your: "محفظة",
      portfolio: "استثمار الذهب",
      special: "الخاصة بك",
      enjoy: "استمتع بمعاملات",
      safe: "آمنة",
      easy: "وسهولة",
      management: " إدارة محفظتك ",
      enjoyA: "استمتع بتجربة ",
      seamless: "سهلة ورائعة",
    },
    section3: {
      what: "ما",
      we: "نقدمه",
      offer: "لك",
      invest: "استثمر في الذهب",
      lowest: "بأقل سعر!",
      buy: "قم بشراء وبيع الذهب",
      prices: "بأسعار لا تقبل المنافسة",
      with: "مع رسوم الخدمة التنافسية لدينا.",
      enjoy: "استمتع",
      user: "بتجربة بسيطة",
      app: "وخالية من التعقيدات.",
      withsabika: "مع",
      sabika: "سبيكة,",
      makes:
        "تملك وبع الذهب بسهولة تامة, وتصفح التطبيق بكل انسابية وتدير استثماراتك بدون عناء.",
    },
    section4: {
      how: "كيفية",
      start: "البدأ؟",
      download: "التنزيل",
      downloadText: "حمل تطبيق سبيكة من متجر التطبيقات الخاص بك",
      signup: "التسجيل",
      signupText: "أنشئ حسابًا وابدأ استثمارك في الذهب!",
      deposit: "أضف أموالاً إلى محفظتك",
      depositText: "حقق أهدافك المالية - أضف أموالاً واستثمر في الذهب",
      trade: "تداول الذهب",
      tradeText: "استمتع بتجربة تداول ذهب سهلة",
    },
    section5: {
      invest: "استثمر بذكاء مع ",
      sabika: "سبيكة",
      give: "امنح",
      future: "مستقبلك",
      financial: "المالي الاستقرار",
    },
    footer: {
      privacy: "سياسة الاستخدام",
      terms: "الشروط والاحكام",
    },
    header: {
      wallet: "المحفظة",
      portfolio: "ذهبي",
      dashboard: "الرئيسية",
      account: "الحساب",
      language: "اللغة",
      logout: "تسجيل الخروج",
    },
    wallet: {
      total: "إجمالي الرصيد",
      totalToolTIp: "هذا هو الرصيد الإجمالي لمحفظتك",
      available: "متاح",
      availableToolTip: "هذا هو المبلغ الإجمالي للأموال التي لديك في محفظتك",
      availableWithDraw: "متاح للسحب",
      availableWithDrawToolTip: "هذا هو المبلغ الإجمالي الذي يمكنك سحبه",
      processing: "جاري التنفيذ",
      processingToolTip:
        "هذا هو المبلغ الإجمالي للأموال التي تتم معالجتها حاليًا",
      totalStorageFees: "إجمالي رسوم التخزين",
      totalStorageFeesToolTip:
        "هذا هو المبلغ الإجمالي للأموال التي قد دفعتها كرسوم تخزين",
      hide: "إخفاء الرصيد",
      add: "إيداع",
      withdraw: "سحب",
      noTransactions: "  لا توجد معاملات",
      moneyHistory: "سجل المعاملات المالية",
      goldHistory: " سجل المعاملات الذهبية",
      deposit: " إيداع",
      purchase: " شراء",
      sell: " بيع",
      seeAll: " اظهر الكل",
      egp: "جنيه  ",
      gram: "جرام",
      grams: "جرام",
      pending: "قيد المراجعة",
      approved: "معاملة ناجحة",
      rejected: "معاملة مرفوضة",
      show: "إظهار الرصيد",
      refund: "استرداد",
      storeFees: "رسوم التخزين",
      buy: "شراء",
      startDate: "تاريخ البدء",
      endDate: "تاريخ الانتهاء",
      reset: " إعادة تعيين",
      cancelationFees: "رسوم الإلغاء",
      transactionDetails: "تفاصيل المعاملة",
      transactionId: "رقم المعاملة",
      transactionDate: "تاريخ المعاملة",
      transactionType: "نوع المعاملة",
      transactionTime: "وقت المعاملة",
      goldPrice: "سعر الذهب",
      totalWeight: "إجمالي الوزن",
      price: "السعر",
      manufacturingFee: "رسوم المصنعية",
      taxes: "الرسوم الضريبية",
      transactionFee: "رسوم المعاملة",
      storageFee: "رسوم التخزين",
      total: "الإجمالي",
      serialNumbers: "أرقام التسلسل",
      filter: "تصفية",
      noTransaction: "لا توجد معاملات",
      noTransactionYet: "لا توجد معاملات بعد",
      transactionStatus: "حالة المعاملة",
      viewSerials: "عرض الأرفام المتسلسلة",
      serialNumber: "الأرقام المتسلسلة",
      noGoldTransactionsYet: "لا توجد معاملات ذهبية بعد",
    },
    dashboard: {
      totalAssets: "الرصيد الإجمالي",
      totalAssetsToolTip: "هذا هو إجمالي الرصيد التي لديك في محفظتك",
      available: "الرصيد المتاح",
      availableToolTip: "هذا هو إجمالي المبلغ المتوفر لديك في محفظتك",
      goldAssets: "ذهبي",
      goldAssetsToolTip: "هذا هو إجمالي كمية الذهب التي لديك في محفظتك",
      processing: "الرصيد قيد المراجعة",
      processingToolTip: "هذا هو إجمالي المبلغ الذي يتم معالجته حالياً",
      lastUpdate: "آخر تحديث في",
      gold24KAskPrice: "شراء 24 قيراط - بدون رسوم",
      gold24KBidPrice: "بيع 24 قيراط - بدون رسوم",
      title: "لوحة التحكم",
      updated: "آخر تحديث لسعر الذهب بتاريخ",
      goldPriceChart: "سعر الذهب",
      gold24KBuy: "شراء 24 قيراط - بدون رسوم",
      gold24KSell: "بيع 24 قيراط - بدون رسوم",
    },
    buySell: {
      totalWeight: "الذهب الخاص بك",
      available: "الرصيد المتاح",
      buy: "شراء",
      sell: "بيع",
      weight: "وزن",
      weightPlaceholder: "ادخل الوزن",
      moneyPlaceholder: "ادخل المبلغ",
      money: "المبلغ",
      sellAll: "بيع الكل",
      grams: "جرام",
      egp: "جنيه  ",
      min: "الحد الأدنى",
      minSell: "لا يمكن البيع بأقل من",
      max: "الحد الأقصى",
      showBalance: "إظهار الرصيد",
      hideBalance: "إخفاء الرصيد",
      goldFractionCalculator: "حاسبة الذهب ",
    },
    pinCode: {
      title: ".يرجي إدخال الرمز السري للمتابعة",
      cancel: "إلغاء",
      confirm: "تأكيد",
      confirmPayment: "تأكيد الدفع",
      wrongPin: "الرمز السري غير صحيح",
    },
    purchase: {
      confirmBuy: "تأكيد الشراء",
      confirmSell: "تأكيد البيع",
      secureGold:
        "يتم تخزين ذهبك بشكل آمن في البنك المركزي المصري.نود إعلامك بأن خدمة توصيل أجزاء الذهب غير متوفرة.",
      sellTalk:
        "يتوجب عليك سحب أموالك في غضون شهرين بعد البيع. وإلا، سيتم تحويلها تلقائيًا إلى حسابك المصرفي.",
      voucher: "أدخل كود الخصم",
      successVoucher: "تم تطبيق كود الخصم علي طلبك.",
      failedVoucher: "كود القسيمة الذي أدخلته غير صحيح",
      goldPrice: "سعر الذهب",
      totalWeight: "إجمالي الوزن",
      valueOfGold: "قيمة الذهب",
      manufacturingFees: "رسوم المصنعية",
      Taxes: "الضرائب",
      TransactionFee: "رسوم المعاملة",
      StorageFee: "رسوم التخزين",
      total: "الإجمالي",
      Discount: "الخصم  ",
      Amount: "المبلغ المستحق",
      confirmPayment: "تأكيد الدفع",
      apply: "أضف القسيمة",
      amountWeReceive: "المبلغ الذي ستستلمه",
      current: "سعر الذهب الحالي",
      totalWeightToSell: "إجمالي الوزن للبيع",
      yourPurchase: "!تهانينا! تم الشراء بنجاح",
      addedGold: "تم إضافة",
      gramOfGold: "جرام من الذهب الذي اشتريته إلي ذهبك",
      portfolio: "ذهبي",
      yourGold: "!تم بيع الذهب بنجاح",
      yourGoldSale: "تم بيع الذهب بنجاح, وتمت إضافة الأموال إلي محفظتك.",
      wallet: "عرض المحفظة",
      viewTransaction: "عرض المعاملة",
    },
    login: {
      welcome: "مرحباً بك في",
      sabika: "سبيكة",
      join: "قم بتسجيل الدخول للوصول الي حسابك واستكشاف خدماتنا",
      phoneOrEmail: "رقم الهاتف أو البريد الإلكتروني",
      invalid: "رقم الهاتف أو البريد الإلكتروني غير صحيح",
      login: "تسجيل الدخول",
      buySell: "شراء وبيع الذهب",
      fraction: "جزيئات",
      track: "تتبع",
      Your: "استثمارك",
      portfolio: "الذهبي",
      secure: "آمن",
      Transactions: "المعاملات والمحفظة",
      Management: "الإدارة",
      join: "انضم",
      for: "لتجربة",
      toSabika:'لسبيكة',
      seamless: "سهلة وموثوقة ومتوافقة مع الشريعة",
      Journey: "الاستثمارية",
    },
    otp: {
      verify: "إدخال رمز التحقق",
      enter:
        "لقد أرسلنا إليك رمز تحقق لمرة واحدة (OTP).أدخل الرمز أدناه لتأكيد هويتك.",
      verifyButton: "تحقق",
      receive: " لم يصلك الرمز؟",
      resend: "أعد إرسال رمز التحقق",
      wrong: "رمز التحقق غير صحيح",
      fill: "يرجى ملء جميع الحقول",
    },
  },
  // eg: {
  //   navbar: {
  //     home: "الرئيسيه",
  //     features: "المميزات",
  //     howitworks: "ابدأ ازاي",
  //     download: "تنزيل",
  //     signup: "تسجيل الدخول",
  //     login: "تسجيل الدخول",

  //     lang: "English",
  //   },
  //   section1: {
  //     unlock: "اكتشف",
  //     potential: "معانا",
  //     gold: "الدهب",
  //     text: "هنخلى الاستثمار فى الدهب ابسط و اسهل.",
  //     download: "نزل التطبيق",
  //     goldPriceUpdate: "تم تحديث سعر الذهب",
  //     buy: "شراء - 24K (بدون رسوم)",
  //     sell: "بيع - 24K (بدون رسوم)",
  //     egp: "جنيه مصري",
  //   },
  //   section2: {
  //     why: "ليه",
  //     sabika: "سبيكة ؟",
  //     buy: "بيع و اشتري",
  //     fraction: "أجزاء من الدهب.",
  //     track: "تقدر تتابع",
  //     your: "محفظة استثمارك.",
  //     buyWith: "اشتري بكل",
  //     safe: "أمان",
  //     easy: "واتحكم",
  //     management: "بمحفظتك.",
  //     enjoyA: "استمتع",
  //     witheasy: "بأسهل",
  //     seamless: "تجربة.",
  //   },
  //   section3: {
  //     what: "بنقدملك",
  //     we: "ايه؟",
  //     offer: "لك",
  //     invest: "استثمار في الدهب",
  //     lowest: "بأقل سعر!",
  //     lowest2: "بأقل سعر",
  //     buy: "هتشتري الدهب",
  //     prices: "بأسعار لا تقبل المنافسة",
  //     with: "مع رسوم متقبلش المنافسة.",
  //     enjoy: "أسهل تجربة",
  //     user: "بتجربة بسيطة",
  //     app: "بدون اي مشاكل",
  //     withsabika: "مع",
  //     sabika: "سبيكة,",
  //     makes: "هتقدر تشتري وتبيع بكل سهولة وتابع استثمارك علي طول.",
  //   },
  //   section4: {
  //     how: "ابدأ",
  //     start: "ازاي؟",
  //     download: "نزل",
  //     downloadText: "نزل سبيكة من متجر التطبيقات بتاعك",
  //     signup: "سجل",
  //     signupText: "اعمل حسابك وابدأ استثمارك في الدهب على طول",
  //     deposit: "ضيف فلوس لمحفظتك",
  //     depositText: "ضيف فلوس و ابدأ استثمار",
  //     trade: "اشترى وبيع",
  //     tradeText: "اشترى و بيع بكل سهولة",
  //   },
  //   section5: {
  //     invest: "استثمر بذكاء مع ",
  //     sabika: "سبيكة",
  //     give: "امنح",
  //     future: "مستقبلك",
  //     financial: "المالي الاستقرار",
  //   },
  //   footer: {
  //     privacy: "سياسة الاستخدام",
  //     terms: "الشروط والاحكام",
  //   },
  //   header: {
  //     wallet: "المحفظة",
  //     portfolio: "ذهبي",
  //     dashboard: "الرئيسية",
  //     account: "الحساب",
  //     language: "اللغة",
  //     logout: "تسجيل الخروج",
  //   },
  //   wallet: {
  //     total: "إجمالي الرصيد",
  //     totalToolTIp: "هذا هو الرصيد الإجمالي لمحفظتك",
  //     available: "متاح",
  //     availableToolTip: "هذا هو المبلغ الإجمالي للأموال التي لديك في محفظتك",
  //     availableWithDraw: "متاح للسحب",
  //     availableWithDrawToolTip: "هذا هو المبلغ الإجمالي الذي يمكنك سحبه",
  //     processing: "جاري التنفيذ",
  //     processingToolTip:
  //       "هذا هو المبلغ الإجمالي للأموال التي تتم معالجتها حاليًا",
  //     totalStorageFees: "إجمالي رسوم التخزين",
  //     totalStorageFeesToolTip:
  //       "هذا هو المبلغ الإجمالي للأموال التي قد دفعتها كرسوم تخزين",
  //     hide: "إخفاء الرصيد",
  //     add: "إضافة رصيد",
  //     withdraw: "سحب الرصيد",
  //     moneyHistory: "سجل المعاملات المالية",
  //     goldHistory: " سجل المعاملات الذهبية",
  //     deposit: " إيداع",
  //     purchase: " شراء",
  //     sell: " بيع",
  //     seeAll: " اظهر الكل",
  //     egp: "جنيه مصري",
  //     gram: "جرام",
  //     pending: "قيد الانتظار",
  //     approved: "تم الموافقة",
  //     rejected: "تم الرفض",
  //     show: "إظهار الرصيد",
  //     refund: "استرداد",
  //     storeFees: "رسوم التخزين",
  //     buy: "شراء",
  //     cancelationFees: "رسوم الإلغاء",
  //   },
  //   dashboard: {
  //     totalAssets: "إجمالي الأصول",
  //     totalAssetsToolTip: "هذا هو إجمالي الأصول التي لديك في محفظتك",
  //     available: "المتوفر",
  //     availableToolTip: "هذا هو إجمالي المبلغ المتوفر لديك في محفظتك",
  //     goldAssets: "أصول الذهب",
  //     goldAssetsToolTip: "هذا هو إجمالي كمية الذهب التي لديك في محفظتك",
  //     processing: "قيد المعالجة",
  //     processingToolTip: "هذا هو إجمالي المبلغ الذي يتم معالجته حالياً",
  //     lastUpdate: "آخر تحديث في",
  //     gold24KAskPrice: "سعر الذهب 24K",
  //     gold24KBidPrice: "سعر البيع 24K",
  //     title: "لوحة التحكم",
  //   },
  // },
};

const useLanguage = create((set) => ({
  language:
    typeof window !== "undefined" && localStorage.getItem("language")
      ? localStorage.getItem("language")
      : "en",
  translations: translations,
  setLanguage: (lang) => {
    if (typeof window !== "undefined") {
      localStorage.setItem("language", lang);
    }
    set({ language: lang });
  },
}));

export default useLanguage;
